pool:
  vmImage: ubuntu-20.04

steps:
- script: |
    curl -L https://nixos.org/nix/install | sh
    . ~/.nix-profile/etc/profile.d/nix.sh
  displayName: 'Install Nix'
- script: |
    . ~/.nix-profile/etc/profile.d/nix.sh
    nix-build
  displayName: 'Build'
